# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '20181026-SushreeSangitaN-NYCSchools' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 20181026-SushreeSangitaN-NYCSchools

  target '20181026-SushreeSangitaN-NYCSchoolsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '20181026-SushreeSangitaN-NYCSchoolsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'SwiftyJSON'
pod 'Alamofire'

end
